### ISSUE TITLE
Exposing barBorder property or attributes in track options menu

### ISSUE THREAD

**Issue by alexpreynolds** [higlass/higlass-multivec#25]
Wouter noted that the black border around multivec track elements makes the component elements more difficult to view when narrow. 

I think can go into the view configuration JSON and specify it manually, and I was able to disable it by manually editing the local copy of the multivec plugin, but to help him explore different combinations I'd like to ask if the `barBorder` property could perhaps be exposed in the dropdown options menu for the multivec track, to either enable/disable it (`true`/`false`) or to expose color and/or opacity?

**Comment by alexpreynolds** [comment]
This might be something I could take a stab at, as well. Just wanted to ask if this is something you think is a desired feature.

**Comment by pkerpedjiev** [comment]
Is it not already exposed?

![image](https://user-images.githubusercontent.com/2143629/47394768-10f93f80-d6f2-11e8-926c-241e6debf0fb.png)

In general, available track menu options are defined here: https://github.com/higlass/higlass/blob/03f519175fa56e7f98c8d0cb5e55fb9751ec7b57/app/scripts/configs/options-info.js#L215

To define available option values, they would have to be set in the track somewhere around here: https://github.com/higlass/higlass-multivec/blob/1be334a27e980f9498192ca662d1aaef71de07e3/src/scripts/StackedBarTrack.js#L665

And there would probably need to be a little plumbing added to HiGlass to load available option values from plugin tracks here:
https://github.com/higlass/higlass/blob/03f519175fa56e7f98c8d0cb5e55fb9751ec7b57/app/scripts/SeriesListMenu.js#L24

Since you are the main users of this, it's up to you whether you want to add the option. If you submit a PR, I'm happy to merge it.

**Comment by alexpreynolds** [comment]
I'm very sorry — I completely missed this. I'll close this up.
